// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqxEHvrwveLJcqyzlS0iYDrF_JRHgxB0M',
    appId: '1:906383105561:android:a77b69a4bbf4eba89e5488',
    messagingSenderId: '906383105561',
    projectId: 'cipherschools-assignment-aeca5',
    storageBucket: 'cipherschools-assignment-aeca5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAisnzouYpcdIDZ6_TV73EYMf76bjVCp6A',
    appId: '1:906383105561:ios:8a8c8f9090e80f3a9e5488',
    messagingSenderId: '906383105561',
    projectId: 'cipherschools-assignment-aeca5',
    storageBucket: 'cipherschools-assignment-aeca5.appspot.com',
    iosClientId: '906383105561-te2lodniv3rb9gu70m2vfrhok294baid.apps.googleusercontent.com',
    iosBundleId: 'com.example.cipherSchoolsExpenseTracker',
  );
}
